# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './FilmEditorUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FilmDialog(object):
    def setupUi(self, FilmDialog):
        FilmDialog.setObjectName("FilmDialog")
        FilmDialog.resize(548, 604)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(FilmDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filmList = QtWidgets.QListView(FilmDialog)
        self.filmList.setObjectName("filmList")
        self.horizontalLayout_2.addWidget(self.filmList)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newFilm = QtWidgets.QPushButton(FilmDialog)
        self.newFilm.setObjectName("newFilm")
        self.verticalLayout_2.addWidget(self.newFilm)
        self.deleteFilm = QtWidgets.QPushButton(FilmDialog)
        self.deleteFilm.setObjectName("deleteFilm")
        self.verticalLayout_2.addWidget(self.deleteFilm)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(FilmDialog)
        self.groupBox.setEnabled(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.titleLabel = QtWidgets.QLabel(self.groupBox)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.titleLabel)
        self.titleEdit = QtWidgets.QLineEdit(self.groupBox)
        self.titleEdit.setObjectName("titleEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titleEdit)
        self.timeLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLabel.sizePolicy().hasHeightForWidth())
        self.timeLabel.setSizePolicy(sizePolicy)
        self.timeLabel.setObjectName("timeLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.timeLabel)
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit.sizePolicy().hasHeightForWidth())
        self.timeEdit.setSizePolicy(sizePolicy)
        self.timeEdit.setTime(QtCore.QTime(20, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timeEdit)
        self.ratingLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ratingLabel.sizePolicy().hasHeightForWidth())
        self.ratingLabel.setSizePolicy(sizePolicy)
        self.ratingLabel.setObjectName("ratingLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ratingLabel)
        self.ratingComboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ratingComboBox.sizePolicy().hasHeightForWidth())
        self.ratingComboBox.setSizePolicy(sizePolicy)
        self.ratingComboBox.setObjectName("ratingComboBox")
        self.ratingComboBox.addItem("")
        self.ratingComboBox.addItem("")
        self.ratingComboBox.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ratingComboBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addPosterButton = QtWidgets.QPushButton(self.groupBox)
        self.addPosterButton.setObjectName("addPosterButton")
        self.horizontalLayout.addWidget(self.addPosterButton)
        self.addTrailerButton = QtWidgets.QPushButton(self.groupBox)
        self.addTrailerButton.setObjectName("addTrailerButton")
        self.horizontalLayout.addWidget(self.addTrailerButton)
        self.addMovieButton = QtWidgets.QPushButton(self.groupBox)
        self.addMovieButton.setObjectName("addMovieButton")
        self.horizontalLayout.addWidget(self.addMovieButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pizzaCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.pizzaCheckBox.setMinimumSize(QtCore.QSize(0, 0))
        self.pizzaCheckBox.setObjectName("pizzaCheckBox")
        self.verticalLayout.addWidget(self.pizzaCheckBox)
        self.pictureLabel = QtWidgets.QLabel(self.groupBox)
        self.pictureLabel.setMinimumSize(QtCore.QSize(200, 200))
        self.pictureLabel.setText("")
        self.pictureLabel.setObjectName("pictureLabel")
        self.verticalLayout.addWidget(self.pictureLabel)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(FilmDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.titleLabel.raise_()
        self.titleEdit.raise_()
        self.ratingComboBox.raise_()
        self.ratingLabel.raise_()
        self.addTrailerButton.raise_()
        self.addMovieButton.raise_()
        self.timeEdit.raise_()
        self.timeLabel.raise_()
        self.buttonBox.raise_()
        self.groupBox.raise_()
        self.addTrailerButton.raise_()
        self.newFilm.raise_()

        self.retranslateUi(FilmDialog)
        QtCore.QMetaObject.connectSlotsByName(FilmDialog)

    def retranslateUi(self, FilmDialog):
        _translate = QtCore.QCoreApplication.translate
        FilmDialog.setWindowTitle(_translate("FilmDialog", "Film Edit"))
        self.newFilm.setText(_translate("FilmDialog", "Add New Film"))
        self.deleteFilm.setText(_translate("FilmDialog", "Delete Film"))
        self.groupBox.setTitle(_translate("FilmDialog", "Current Film Detail"))
        self.titleLabel.setText(_translate("FilmDialog", "Title"))
        self.timeLabel.setText(_translate("FilmDialog", "Time"))
        self.ratingLabel.setText(_translate("FilmDialog", "Rating"))
        self.ratingComboBox.setItemText(0, _translate("FilmDialog", "PG 12"))
        self.ratingComboBox.setItemText(1, _translate("FilmDialog", "PG 14"))
        self.ratingComboBox.setItemText(2, _translate("FilmDialog", "18"))
        self.addPosterButton.setText(_translate("FilmDialog", "Add Poster"))
        self.addTrailerButton.setText(_translate("FilmDialog", "Add Trailer"))
        self.addMovieButton.setText(_translate("FilmDialog", "Add Main Feature"))
        self.pizzaCheckBox.setText(_translate("FilmDialog", "&Pizza"))

